version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fb-weather-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9ltz793xkajj"
s3_prefix = "fb-weather-bot"
region = "eu-central-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
