AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fb-weather-bot

Globals:
  Function:
    Timeout: 10
    Tracing: Active

Resources:
  WeatherBotFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/SecretsManagerReadWrite'

  WeatherBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Role: !GetAtt WeatherBotFunctionIamRole.Arn
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        WeatherBot:
          Type: Schedule
          Properties:
            Schedule: cron(0 7,15 * * ? *)
            Enabled: True

Outputs:
  WeatherBotFunction:
    Description: "Weather Bot Lambda Function ARN"
    Value: !GetAtt WeatherBotFunction.Arn
  WeatherBotFunctionIamRole:
    Description: "Implicit IAM Role created for Weather Bot function"
    Value: !GetAtt WeatherBotFunctionIamRole.Arn
